defmodule ExDNA.Reporter.HTML do
  @moduledoc """
  Generates a self-contained HTML report file for clone detection results.

  Writes `ex_dna_report.html` to the current directory.
  """

  @behaviour ExDNA.Reporter

  alias ExDNA.Detection.Clone

  @output_file "ex_dna_report.html"

  @impl true
  def report(%ExDNA.Report{} = report) do
    html = build_html(report)
    File.write!(@output_file, html)
    IO.puts("  HTML report written to #{@output_file}")
    :ok
  end

  defp build_html(%ExDNA.Report{clones: clones, stats: stats}) do
    clone_cards =
      clones
      |> Enum.with_index(1)
      |> Enum.map_join("\n", fn {clone, idx} -> render_clone(clone, idx) end)

    """
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ExDNA Report</title>
    <style>
    #{css()}
    </style>
    </head>
    <body>
    <header>
      <h1>ExDNA</h1>
      <p class="subtitle">Code Duplication Report</p>
    </header>
    <section class="summary">
      <div class="stat">
        <span class="stat-value">#{stats.files_analyzed}</span>
        <span class="stat-label">Files analyzed</span>
      </div>
      <div class="stat">
        <span class="stat-value">#{stats.total_clones}</span>
        <span class="stat-label">Clones found</span>
      </div>
      <div class="stat">
        <span class="stat-value">#{stats.type_i_count}</span>
        <span class="stat-label">Type I (exact)</span>
      </div>
      <div class="stat">
        <span class="stat-value">#{stats.type_ii_count}</span>
        <span class="stat-label">Type II (renamed)</span>
      </div>
      <div class="stat">
        <span class="stat-value">#{Map.get(stats, :type_iii_count, 0)}</span>
        <span class="stat-label">Type III (near-miss)</span>
      </div>
      <div class="stat">
        <span class="stat-value">~#{stats.total_duplicated_lines}</span>
        <span class="stat-label">Duplicated lines</span>
      </div>
    </section>
    #{if clones == [], do: ~s(<p class="no-clones">✓ No code duplication detected</p>), else: clone_cards}
    <footer>Generated by ExDNA</footer>
    </body>
    </html>
    """
  end

  defp render_clone(clone, index) do
    badge = type_badge(clone.type)
    sim = format_similarity(clone.similarity)

    locations =
      Enum.map_join(clone.fragments, "\n", fn frag ->
        path = relative_path(frag.file)
        label = if frag.line > 0, do: "#{path}:#{frag.line}", else: path

        ~s(<a class="location" href="#">#{escape(label)}</a>)
      end)

    snippets_list = Clone.source_snippets(clone)

    snippets =
      snippets_list
      |> Enum.with_index(1)
      |> Enum.map_join("\n", fn {snippet, i} ->
        label = if length(snippets_list) > 1, do: "Fragment #{i}", else: ""

        """
        <div class="snippet">
          #{if label != "", do: ~s(<div class="snippet-label">#{label}</div>), else: ""}
          <pre><code>#{highlight(snippet)}</code></pre>
        </div>
        """
      end)

    suggestion_html = render_suggestion(clone.suggestion)
    behaviour_html = render_behaviour_suggestion(clone.behaviour_suggestion)

    """
    <details class="clone-card" open>
      <summary>
        <span class="badge #{badge_class(clone.type)}">#{badge}</span>
        <span class="clone-title">##{index}</span>
        <span class="meta">#{clone.mass} nodes#{sim}</span>
      </summary>
      <div class="clone-body">
        <div class="locations">#{locations}</div>
        #{snippets}
        #{suggestion_html}
        #{behaviour_html}
      </div>
    </details>
    """
  end

  defp render_suggestion(nil), do: ""

  defp render_suggestion(%{kind: :extract_function} = s) do
    params = Enum.join(s.params, ", ")

    call_sites =
      Enum.map_join(s.call_sites, "\n", fn site ->
        ~s(<div class="call-site">#{escape(relative_path(site.file))}:#{site.line} → <code>#{escape(site.call)}</code></div>)
      end)

    """
    <div class="suggestion">
      <div class="suggestion-header">→ Extract function</div>
      <code class="suggestion-sig">defp #{escape(s.name)}(#{escape(params)})</code>
      #{call_sites}
    </div>
    """
  end

  defp render_suggestion(%{kind: :extract_macro} = s) do
    params = if s.params == [], do: "", else: Enum.join(s.params, ", ")
    count = Map.get(s, :occurrence_count, 0)

    """
    <div class="suggestion">
      <div class="suggestion-header">→ Consider macro</div>
      <code class="suggestion-sig">defmacro #{escape(s.name)}(#{escape(params)})</code>
      <div class="call-site">#{count} occurrences across modules</div>
    </div>
    """
  end

  defp render_behaviour_suggestion(nil), do: ""

  defp render_behaviour_suggestion(%{
         callback_name: name,
         callback_arity: arity,
         modules: modules
       }) do
    args = List.duplicate("term()", arity) |> Enum.join(", ")
    mods = Enum.join(modules, ", ")

    """
    <div class="suggestion" style="border-left-color: #61afef;">
      <div class="suggestion-header">→ Consider behaviour</div>
      <code class="suggestion-sig">@callback #{escape(to_string(name))}(#{args})</code>
      <div class="call-site">Implemented identically in #{escape(mods)}</div>
    </div>
    """
  end

  defp type_badge(:type_i), do: "I"
  defp type_badge(:type_ii), do: "II"
  defp type_badge(:type_iii), do: "≈"

  defp badge_class(:type_i), do: "badge-i"
  defp badge_class(:type_ii), do: "badge-ii"
  defp badge_class(:type_iii), do: "badge-iii"

  defp format_similarity(nil), do: ""
  defp format_similarity(sim), do: "  #{Float.round(sim * 100, 1)}%"

  defp relative_path(path) do
    case File.cwd() do
      {:ok, cwd} -> Path.relative_to(path, cwd)
      _ -> path
    end
  end

  defp escape(text) do
    text
    |> to_string()
    |> String.replace("&", "&amp;")
    |> String.replace("<", "&lt;")
    |> String.replace(">", "&gt;")
    |> String.replace("\"", "&quot;")
  end

  defp highlight(code) do
    code
    |> escape()
    |> highlight_comments()
    |> highlight_strings()
    |> highlight_atoms()
    |> highlight_keywords()
    |> highlight_module_names()
  end

  defp highlight_comments(code) do
    Regex.replace(~r/(#[^\n]*)/, code, ~s(<span class="cm">\\1</span>))
  end

  defp highlight_strings(code) do
    Regex.replace(~r/(&quot;(?:[^&]|&(?!quot;))*&quot;)/, code, ~s(<span class="st">\\1</span>))
  end

  defp highlight_atoms(code) do
    Regex.replace(~r/(:[\w?!]+)/, code, ~s(<span class="at">\\1</span>))
  end

  @keywords ~w(def defp defmodule defmacro defmacrop defstruct defprotocol defimpl
               do end if else cond case when fn with for unless raise
               try catch rescue after import use alias require
               and or not in true false nil)

  defp highlight_keywords(code) do
    pattern = @keywords |> Enum.join("|") |> then(&"\\b(#{&1})\\b")
    Regex.replace(Regex.compile!(pattern), code, ~s(<span class="kw">\\1</span>))
  end

  defp highlight_module_names(code) do
    Regex.replace(~r/\b([A-Z]\w+)/, code, ~s(<span class="mn">\\1</span>))
  end

  defp css do
    """
    *{margin:0;padding:0;box-sizing:border-box}
    :root{
      --bg:#1a1a2e;--surface:#16213e;--border:#2a2a4a;
      --text:#e0e0e0;--text-dim:#888;--accent:#7c3aed;
      --red:#ef4444;--yellow:#eab308;--magenta:#d946ef;
      --green:#22c55e;--blue:#60a5fa;--cyan:#22d3ee;
    }
    @media(prefers-color-scheme:light){
      :root{
        --bg:#f8f9fa;--surface:#fff;--border:#e0e0e0;
        --text:#1a1a1a;--text-dim:#666;--accent:#7c3aed;
        --red:#dc2626;--yellow:#ca8a04;--magenta:#c026d3;
        --green:#16a34a;--blue:#2563eb;--cyan:#0891b2;
      }
    }
    body{font-family:system-ui,-apple-system,sans-serif;background:var(--bg);color:var(--text);max-width:900px;margin:0 auto;padding:2rem 1rem}
    header{margin-bottom:2rem}
    h1{font-size:1.5rem;color:var(--accent)}
    .subtitle{color:var(--text-dim);font-size:.9rem}
    .summary{display:flex;flex-wrap:wrap;gap:1rem;margin-bottom:2rem}
    .stat{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:1rem 1.25rem;min-width:120px;flex:1}
    .stat-value{display:block;font-size:1.5rem;font-weight:700}
    .stat-label{font-size:.75rem;color:var(--text-dim);text-transform:uppercase;letter-spacing:.05em}
    .no-clones{color:var(--green);font-size:1.1rem;padding:2rem 0}
    .clone-card{background:var(--surface);border:1px solid var(--border);border-radius:8px;margin-bottom:1rem;overflow:hidden}
    .clone-card summary{cursor:pointer;padding:1rem;display:flex;align-items:center;gap:.75rem;list-style:none}
    .clone-card summary::-webkit-details-marker{display:none}
    .clone-card summary::before{content:"▸";color:var(--text-dim);transition:transform .15s}
    .clone-card[open] summary::before{transform:rotate(90deg)}
    .badge{font-size:.7rem;font-weight:700;padding:2px 8px;border-radius:4px;font-family:monospace}
    .badge-i{background:var(--red);color:#fff}
    .badge-ii{background:var(--yellow);color:#000}
    .badge-iii{background:var(--magenta);color:#fff}
    .clone-title{font-weight:600}
    .meta{color:var(--text-dim);font-size:.85rem;margin-left:auto}
    .clone-body{padding:0 1rem 1rem}
    .locations{margin-bottom:.75rem}
    .location{display:block;color:var(--cyan);font-size:.85rem;font-family:monospace;text-decoration:none;padding:2px 0}
    .location:hover{text-decoration:underline}
    .snippet{margin-bottom:.75rem}
    .snippet-label{font-size:.7rem;color:var(--text-dim);text-transform:uppercase;margin-bottom:4px}
    pre{background:var(--bg);border:1px solid var(--border);border-radius:6px;padding:.75rem 1rem;overflow-x:auto;font-size:.8rem;line-height:1.5}
    code{font-family:'SF Mono',Monaco,Consolas,'Liberation Mono',monospace}
    .kw{color:var(--accent);font-weight:600}
    .st{color:var(--green)}
    .at{color:var(--blue)}
    .cm{color:var(--text-dim);font-style:italic}
    .mn{color:var(--yellow)}
    .suggestion{border-top:1px solid var(--border);margin-top:.75rem;padding-top:.75rem}
    .suggestion-header{color:var(--green);font-weight:600;margin-bottom:.25rem}
    .suggestion-sig{font-size:.85rem;display:block;margin-bottom:.5rem;color:var(--green)}
    .call-site{font-size:.8rem;color:var(--text-dim);padding:2px 0}
    .call-site code{color:var(--cyan)}
    footer{margin-top:3rem;text-align:center;color:var(--text-dim);font-size:.75rem}
    """
  end
end
